Integrating SPAdes using PyDoit
SGBC/capture pull request #5
Opened 2018-05-23 14:16 UTC by RVanDamme

2018-05-28 14:39 UTC, HadrienG submitted a review, later dismissed

2018-05-28 14:39 UTC, HadrienG commented on capture/app.py
> +            rndseed = rnd.randint(1, 1000000)
I'd like to have a real fixed seed with `random.seed(1)`

2018-05-28 14:39 UTC, HadrienG commented on capture/parse.py
> +def parse_fq(output, file, type_f, num_sub, number_records, handle):
This breaks the unit testing. Please add the correct handle argument to the test suite

2018-05-28 14:39 UTC, HadrienG commented
I may have a faster way to select random reads. We can talk about it tomorrow afternoon

2018-05-30 07:07 UTC, HadrienG commented
@RVanDamme Can you create unit tests for the new functions?

2018-06-04 14:51 UTC, HadrienG requested changes

2018-06-04 14:51 UTC, HadrienG commented on capture/parse.py
> +    if sub_rec != []:
`if sub_rec` should work and is arguably better syntax

2018-06-04 14:51 UTC, HadrienG commented on capture/parse.py
> +            if c < number_records*c_sub:
space around operators

2018-06-04 14:51 UTC, HadrienG commented on capture/run_doit.py
> +#!/usr/bin/env python
calling this file `tasks` or `jobs` might be more in line with a workflow manager / the doit vocabulary

2018-06-04 14:51 UTC, HadrienG commented on capture/external_run.py
> +#!/usr/bin/env python
rename `run.py`

2018-06-07 08:25 UTC, HadrienG commented
@RVanDamme ready to merge and move on to contig overlap?

2018-06-07 09:21 UTC, RVanDamme commented
@HadrienG yes, it seems the SPAdes part is complete for now

2018-06-08 09:32 UTC, HadrienG approved these changes

2018-06-08 09:32 UTC, merged